ARG BASE_DOCKER
# Dockerfile that updates the container with new code.
# SageMaker PyTorch image
FROM ${BASE_DOCKER}

# /opt/ml and all subdirectories are utilized by SageMaker, use the /code subdirectory to store your user code.
COPY . /opt/ml/code/

# RUN pip install -e /opt/ml/code/

# Prevent sagemaker from installing requirements again.
RUN pip install s3fs>=2023.6.0
RUN pip install --upgrade s3fs
RUN rm /opt/ml/code/setup.py
RUN rm /opt/ml/code/requirements.txt

ENV SAGEMAKER_PROGRAM open_lm/main.py
